// Code generated by mockery. DO NOT EDIT.

package encryption

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Encryptor is an autogenerated mock type for the Encryptor type
type Encryptor struct {
	mock.Mock
}

type Encryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *Encryptor) EXPECT() *Encryptor_Expecter {
	return &Encryptor_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: ctx, persistenceID, ciphertext, keyID
func (_m *Encryptor) Decrypt(ctx context.Context, persistenceID string, ciphertext []byte, keyID string) ([]byte, error) {
	ret := _m.Called(ctx, persistenceID, ciphertext, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) ([]byte, error)); ok {
		return rf(ctx, persistenceID, ciphertext, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) []byte); ok {
		r0 = rf(ctx, persistenceID, ciphertext, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = rf(ctx, persistenceID, ciphertext, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encryptor_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type Encryptor_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - persistenceID string
//   - ciphertext []byte
//   - keyID string
func (_e *Encryptor_Expecter) Decrypt(ctx interface{}, persistenceID interface{}, ciphertext interface{}, keyID interface{}) *Encryptor_Decrypt_Call {
	return &Encryptor_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, persistenceID, ciphertext, keyID)}
}

func (_c *Encryptor_Decrypt_Call) Run(run func(ctx context.Context, persistenceID string, ciphertext []byte, keyID string)) *Encryptor_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *Encryptor_Decrypt_Call) Return(plaintext []byte, err error) *Encryptor_Decrypt_Call {
	_c.Call.Return(plaintext, err)
	return _c
}

func (_c *Encryptor_Decrypt_Call) RunAndReturn(run func(context.Context, string, []byte, string) ([]byte, error)) *Encryptor_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: ctx, persistenceID, plaintext
func (_m *Encryptor) Encrypt(ctx context.Context, persistenceID string, plaintext []byte) ([]byte, string, error) {
	ret := _m.Called(ctx, persistenceID, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) ([]byte, string, error)); ok {
		return rf(ctx, persistenceID, plaintext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) []byte); ok {
		r0 = rf(ctx, persistenceID, plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) string); ok {
		r1 = rf(ctx, persistenceID, plaintext)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []byte) error); ok {
		r2 = rf(ctx, persistenceID, plaintext)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Encryptor_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type Encryptor_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - persistenceID string
//   - plaintext []byte
func (_e *Encryptor_Expecter) Encrypt(ctx interface{}, persistenceID interface{}, plaintext interface{}) *Encryptor_Encrypt_Call {
	return &Encryptor_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, persistenceID, plaintext)}
}

func (_c *Encryptor_Encrypt_Call) Run(run func(ctx context.Context, persistenceID string, plaintext []byte)) *Encryptor_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *Encryptor_Encrypt_Call) Return(ciphertext []byte, keyID string, err error) *Encryptor_Encrypt_Call {
	_c.Call.Return(ciphertext, keyID, err)
	return _c
}

func (_c *Encryptor_Encrypt_Call) RunAndReturn(run func(context.Context, string, []byte) ([]byte, string, error)) *Encryptor_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewEncryptor creates a new instance of Encryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Encryptor {
	mock := &Encryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
