// Code generated by mockery. DO NOT EDIT.

package encryption

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// KeyStore is an autogenerated mock type for the KeyStore type
type KeyStore struct {
	mock.Mock
}

type KeyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyStore) EXPECT() *KeyStore_Expecter {
	return &KeyStore_Expecter{mock: &_m.Mock}
}

// DeleteKey provides a mock function with given fields: ctx, persistenceID
func (_m *KeyStore) DeleteKey(ctx context.Context, persistenceID string) error {
	ret := _m.Called(ctx, persistenceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, persistenceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KeyStore_DeleteKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKey'
type KeyStore_DeleteKey_Call struct {
	*mock.Call
}

// DeleteKey is a helper method to define mock.On call
//   - ctx context.Context
//   - persistenceID string
func (_e *KeyStore_Expecter) DeleteKey(ctx interface{}, persistenceID interface{}) *KeyStore_DeleteKey_Call {
	return &KeyStore_DeleteKey_Call{Call: _e.mock.On("DeleteKey", ctx, persistenceID)}
}

func (_c *KeyStore_DeleteKey_Call) Run(run func(ctx context.Context, persistenceID string)) *KeyStore_DeleteKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *KeyStore_DeleteKey_Call) Return(_a0 error) *KeyStore_DeleteKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KeyStore_DeleteKey_Call) RunAndReturn(run func(context.Context, string) error) *KeyStore_DeleteKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function with given fields: ctx, keyID
func (_m *KeyStore) GetKey(ctx context.Context, keyID string) ([]byte, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyStore_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type KeyStore_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
func (_e *KeyStore_Expecter) GetKey(ctx interface{}, keyID interface{}) *KeyStore_GetKey_Call {
	return &KeyStore_GetKey_Call{Call: _e.mock.On("GetKey", ctx, keyID)}
}

func (_c *KeyStore_GetKey_Call) Run(run func(ctx context.Context, keyID string)) *KeyStore_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *KeyStore_GetKey_Call) Return(key []byte, err error) *KeyStore_GetKey_Call {
	_c.Call.Return(key, err)
	return _c
}

func (_c *KeyStore_GetKey_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *KeyStore_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateKey provides a mock function with given fields: ctx, persistenceID
func (_m *KeyStore) GetOrCreateKey(ctx context.Context, persistenceID string) (string, []byte, error) {
	ret := _m.Called(ctx, persistenceID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateKey")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, []byte, error)); ok {
		return rf(ctx, persistenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, persistenceID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []byte); ok {
		r1 = rf(ctx, persistenceID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, persistenceID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// KeyStore_GetOrCreateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateKey'
type KeyStore_GetOrCreateKey_Call struct {
	*mock.Call
}

// GetOrCreateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - persistenceID string
func (_e *KeyStore_Expecter) GetOrCreateKey(ctx interface{}, persistenceID interface{}) *KeyStore_GetOrCreateKey_Call {
	return &KeyStore_GetOrCreateKey_Call{Call: _e.mock.On("GetOrCreateKey", ctx, persistenceID)}
}

func (_c *KeyStore_GetOrCreateKey_Call) Run(run func(ctx context.Context, persistenceID string)) *KeyStore_GetOrCreateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *KeyStore_GetOrCreateKey_Call) Return(keyID string, key []byte, err error) *KeyStore_GetOrCreateKey_Call {
	_c.Call.Return(keyID, key, err)
	return _c
}

func (_c *KeyStore_GetOrCreateKey_Call) RunAndReturn(run func(context.Context, string) (string, []byte, error)) *KeyStore_GetOrCreateKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeyStore creates a new instance of KeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyStore {
	mock := &KeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
