# https://docs.codecov.com/docs/codecov-yaml
coverage:
  precision: 1
  round: down
  range: "70...100"
  project:
    default:
      target: auto
      threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true

ignore:
  - "egopb"
  - "test"
  - "example"
  - "mocks"
