// Code generated by mockery. DO NOT EDIT.

package persistence

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	egopb "github.com/tochemey/ego/v4/egopb"
)

// SnapshotStore is an autogenerated mock type for the SnapshotStore type
type SnapshotStore struct {
	mock.Mock
}

type SnapshotStore_Expecter struct {
	mock *mock.Mock
}

func (_m *SnapshotStore) EXPECT() *SnapshotStore_Expecter {
	return &SnapshotStore_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: ctx
func (_m *SnapshotStore) Connect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SnapshotStore_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type SnapshotStore_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SnapshotStore_Expecter) Connect(ctx interface{}) *SnapshotStore_Connect_Call {
	return &SnapshotStore_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *SnapshotStore_Connect_Call) Run(run func(ctx context.Context)) *SnapshotStore_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SnapshotStore_Connect_Call) Return(_a0 error) *SnapshotStore_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SnapshotStore_Connect_Call) RunAndReturn(run func(context.Context) error) *SnapshotStore_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSnapshots provides a mock function with given fields: ctx, persistenceID, toSequenceNumber
func (_m *SnapshotStore) DeleteSnapshots(ctx context.Context, persistenceID string, toSequenceNumber uint64) error {
	ret := _m.Called(ctx, persistenceID, toSequenceNumber)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSnapshots")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64) error); ok {
		r0 = rf(ctx, persistenceID, toSequenceNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SnapshotStore_DeleteSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSnapshots'
type SnapshotStore_DeleteSnapshots_Call struct {
	*mock.Call
}

// DeleteSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - persistenceID string
//   - toSequenceNumber uint64
func (_e *SnapshotStore_Expecter) DeleteSnapshots(ctx interface{}, persistenceID interface{}, toSequenceNumber interface{}) *SnapshotStore_DeleteSnapshots_Call {
	return &SnapshotStore_DeleteSnapshots_Call{Call: _e.mock.On("DeleteSnapshots", ctx, persistenceID, toSequenceNumber)}
}

func (_c *SnapshotStore_DeleteSnapshots_Call) Run(run func(ctx context.Context, persistenceID string, toSequenceNumber uint64)) *SnapshotStore_DeleteSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint64))
	})
	return _c
}

func (_c *SnapshotStore_DeleteSnapshots_Call) Return(_a0 error) *SnapshotStore_DeleteSnapshots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SnapshotStore_DeleteSnapshots_Call) RunAndReturn(run func(context.Context, string, uint64) error) *SnapshotStore_DeleteSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields: ctx
func (_m *SnapshotStore) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SnapshotStore_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type SnapshotStore_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SnapshotStore_Expecter) Disconnect(ctx interface{}) *SnapshotStore_Disconnect_Call {
	return &SnapshotStore_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *SnapshotStore_Disconnect_Call) Run(run func(ctx context.Context)) *SnapshotStore_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SnapshotStore_Disconnect_Call) Return(_a0 error) *SnapshotStore_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SnapshotStore_Disconnect_Call) RunAndReturn(run func(context.Context) error) *SnapshotStore_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSnapshot provides a mock function with given fields: ctx, persistenceID
func (_m *SnapshotStore) GetLatestSnapshot(ctx context.Context, persistenceID string) (*egopb.Snapshot, error) {
	ret := _m.Called(ctx, persistenceID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSnapshot")
	}

	var r0 *egopb.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*egopb.Snapshot, error)); ok {
		return rf(ctx, persistenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *egopb.Snapshot); ok {
		r0 = rf(ctx, persistenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*egopb.Snapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, persistenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SnapshotStore_GetLatestSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSnapshot'
type SnapshotStore_GetLatestSnapshot_Call struct {
	*mock.Call
}

// GetLatestSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - persistenceID string
func (_e *SnapshotStore_Expecter) GetLatestSnapshot(ctx interface{}, persistenceID interface{}) *SnapshotStore_GetLatestSnapshot_Call {
	return &SnapshotStore_GetLatestSnapshot_Call{Call: _e.mock.On("GetLatestSnapshot", ctx, persistenceID)}
}

func (_c *SnapshotStore_GetLatestSnapshot_Call) Run(run func(ctx context.Context, persistenceID string)) *SnapshotStore_GetLatestSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SnapshotStore_GetLatestSnapshot_Call) Return(_a0 *egopb.Snapshot, _a1 error) *SnapshotStore_GetLatestSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SnapshotStore_GetLatestSnapshot_Call) RunAndReturn(run func(context.Context, string) (*egopb.Snapshot, error)) *SnapshotStore_GetLatestSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *SnapshotStore) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SnapshotStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type SnapshotStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SnapshotStore_Expecter) Ping(ctx interface{}) *SnapshotStore_Ping_Call {
	return &SnapshotStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *SnapshotStore_Ping_Call) Run(run func(ctx context.Context)) *SnapshotStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SnapshotStore_Ping_Call) Return(_a0 error) *SnapshotStore_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SnapshotStore_Ping_Call) RunAndReturn(run func(context.Context) error) *SnapshotStore_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// WriteSnapshot provides a mock function with given fields: ctx, snapshot
func (_m *SnapshotStore) WriteSnapshot(ctx context.Context, snapshot *egopb.Snapshot) error {
	ret := _m.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for WriteSnapshot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *egopb.Snapshot) error); ok {
		r0 = rf(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SnapshotStore_WriteSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSnapshot'
type SnapshotStore_WriteSnapshot_Call struct {
	*mock.Call
}

// WriteSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshot *egopb.Snapshot
func (_e *SnapshotStore_Expecter) WriteSnapshot(ctx interface{}, snapshot interface{}) *SnapshotStore_WriteSnapshot_Call {
	return &SnapshotStore_WriteSnapshot_Call{Call: _e.mock.On("WriteSnapshot", ctx, snapshot)}
}

func (_c *SnapshotStore_WriteSnapshot_Call) Run(run func(ctx context.Context, snapshot *egopb.Snapshot)) *SnapshotStore_WriteSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*egopb.Snapshot))
	})
	return _c
}

func (_c *SnapshotStore_WriteSnapshot_Call) Return(_a0 error) *SnapshotStore_WriteSnapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SnapshotStore_WriteSnapshot_Call) RunAndReturn(run func(context.Context, *egopb.Snapshot) error) *SnapshotStore_WriteSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewSnapshotStore creates a new instance of SnapshotStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnapshotStore {
	mock := &SnapshotStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
