// Code generated by mockery. DO NOT EDIT.

package eventadapter

import (
	mock "github.com/stretchr/testify/mock"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

// EventAdapter is an autogenerated mock type for the EventAdapter type
type EventAdapter struct {
	mock.Mock
}

type EventAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *EventAdapter) EXPECT() *EventAdapter_Expecter {
	return &EventAdapter_Expecter{mock: &_m.Mock}
}

// Adapt provides a mock function with given fields: event, revision
func (_m *EventAdapter) Adapt(event *anypb.Any, revision uint64) (*anypb.Any, error) {
	ret := _m.Called(event, revision)

	if len(ret) == 0 {
		panic("no return value specified for Adapt")
	}

	var r0 *anypb.Any
	var r1 error
	if rf, ok := ret.Get(0).(func(*anypb.Any, uint64) (*anypb.Any, error)); ok {
		return rf(event, revision)
	}
	if rf, ok := ret.Get(0).(func(*anypb.Any, uint64) *anypb.Any); ok {
		r0 = rf(event, revision)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*anypb.Any)
		}
	}

	if rf, ok := ret.Get(1).(func(*anypb.Any, uint64) error); ok {
		r1 = rf(event, revision)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventAdapter_Adapt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Adapt'
type EventAdapter_Adapt_Call struct {
	*mock.Call
}

// Adapt is a helper method to define mock.On call
//   - event *anypb.Any
//   - revision uint64
func (_e *EventAdapter_Expecter) Adapt(event interface{}, revision interface{}) *EventAdapter_Adapt_Call {
	return &EventAdapter_Adapt_Call{Call: _e.mock.On("Adapt", event, revision)}
}

func (_c *EventAdapter_Adapt_Call) Run(run func(event *anypb.Any, revision uint64)) *EventAdapter_Adapt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*anypb.Any), args[1].(uint64))
	})
	return _c
}

func (_c *EventAdapter_Adapt_Call) Return(_a0 *anypb.Any, _a1 error) *EventAdapter_Adapt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventAdapter_Adapt_Call) RunAndReturn(run func(*anypb.Any, uint64) (*anypb.Any, error)) *EventAdapter_Adapt_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventAdapter creates a new instance of EventAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventAdapter {
	mock := &EventAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
