// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: ego/ego.proto

package egopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event defines the event that needs to be persisted onto the events store
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the persistence unique identifier
	PersistenceId string `protobuf:"bytes,1,opt,name=persistence_id,json=persistenceId,proto3" json:"persistence_id,omitempty"`
	// Specifies the sequence number
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Specifies the deletion state
	IsDeleted bool `protobuf:"varint,3,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// the event emitted
	Event *anypb.Any `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	// the state obtained from processing the event
	ResultingState *anypb.Any `protobuf:"bytes,5,opt,name=resulting_state,json=resultingState,proto3" json:"resulting_state,omitempty"`
	// Specifies the timestamp
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Specifies the shard number
	Shard         uint64 `protobuf:"varint,7,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_ego_ego_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetPersistenceId() string {
	if x != nil {
		return x.PersistenceId
	}
	return ""
}

func (x *Event) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Event) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Event) GetEvent() *anypb.Any {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetResultingState() *anypb.Any {
	if x != nil {
		return x.ResultingState
	}
	return nil
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetShard() uint64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

// CommandReply specifies the reply to a command sent to
// the aggregate
type CommandReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the actual command reply
	//
	// Types that are valid to be assigned to Reply:
	//
	//	*CommandReply_StateReply
	//	*CommandReply_ErrorReply
	Reply         isCommandReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReply) Reset() {
	*x = CommandReply{}
	mi := &file_ego_ego_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReply) ProtoMessage() {}

func (x *CommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReply.ProtoReflect.Descriptor instead.
func (*CommandReply) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{1}
}

func (x *CommandReply) GetReply() isCommandReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *CommandReply) GetStateReply() *StateReply {
	if x != nil {
		if x, ok := x.Reply.(*CommandReply_StateReply); ok {
			return x.StateReply
		}
	}
	return nil
}

func (x *CommandReply) GetErrorReply() *ErrorReply {
	if x != nil {
		if x, ok := x.Reply.(*CommandReply_ErrorReply); ok {
			return x.ErrorReply
		}
	}
	return nil
}

type isCommandReply_Reply interface {
	isCommandReply_Reply()
}

type CommandReply_StateReply struct {
	// actual state is wrapped with metadata
	StateReply *StateReply `protobuf:"bytes,1,opt,name=state_reply,json=stateReply,proto3,oneof"`
}

type CommandReply_ErrorReply struct {
	// gRPC failure
	ErrorReply *ErrorReply `protobuf:"bytes,2,opt,name=error_reply,json=errorReply,proto3,oneof"`
}

func (*CommandReply_StateReply) isCommandReply_Reply() {}

func (*CommandReply_ErrorReply) isCommandReply_Reply() {}

// StateReply is a command reply.
// This is reply is used when there is a no-op
type StateReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the persistence unique identifier
	PersistenceId string `protobuf:"bytes,1,opt,name=persistence_id,json=persistenceId,proto3" json:"persistence_id,omitempty"`
	// the entity state
	State *anypb.Any `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Specifies the sequence number
	SequenceNumber uint64 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Specifies the timestamp
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateReply) Reset() {
	*x = StateReply{}
	mi := &file_ego_ego_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReply) ProtoMessage() {}

func (x *StateReply) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReply.ProtoReflect.Descriptor instead.
func (*StateReply) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{2}
}

func (x *StateReply) GetPersistenceId() string {
	if x != nil {
		return x.PersistenceId
	}
	return ""
}

func (x *StateReply) GetState() *anypb.Any {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StateReply) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *StateReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ErrorReply is used when a command processing has
// failed.
type ErrorReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the error message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReply) Reset() {
	*x = ErrorReply{}
	mi := &file_ego_ego_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReply) ProtoMessage() {}

func (x *ErrorReply) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReply.ProtoReflect.Descriptor instead.
func (*ErrorReply) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// NoReply is used when a command does not need a reply
type NoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoReply) Reset() {
	*x = NoReply{}
	mi := &file_ego_ego_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReply) ProtoMessage() {}

func (x *NoReply) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReply.ProtoReflect.Descriptor instead.
func (*NoReply) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{4}
}

// GetStateCommand tells the Aggregate
// to reply with its latest state
type GetStateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateCommand) Reset() {
	*x = GetStateCommand{}
	mi := &file_ego_ego_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateCommand) ProtoMessage() {}

func (x *GetStateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateCommand.ProtoReflect.Descriptor instead.
func (*GetStateCommand) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{5}
}

// Offset defines the projection offset
type Offset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the shard number
	ShardNumber uint64 `protobuf:"varint,1,opt,name=shard_number,json=shardNumber,proto3" json:"shard_number,omitempty"`
	// Specifies the projection name.
	ProjectionName string `protobuf:"bytes,2,opt,name=projection_name,json=projectionName,proto3" json:"projection_name,omitempty"`
	// Specifies the value
	Value int64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// Specifies the timestamp
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offset) Reset() {
	*x = Offset{}
	mi := &file_ego_ego_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offset) ProtoMessage() {}

func (x *Offset) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offset.ProtoReflect.Descriptor instead.
func (*Offset) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{6}
}

func (x *Offset) GetShardNumber() uint64 {
	if x != nil {
		return x.ShardNumber
	}
	return 0
}

func (x *Offset) GetProjectionName() string {
	if x != nil {
		return x.ProjectionName
	}
	return ""
}

func (x *Offset) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Offset) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ProjectionId defines the projection id
type ProjectionId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the projection name
	ProjectionName string `protobuf:"bytes,1,opt,name=projection_name,json=projectionName,proto3" json:"projection_name,omitempty"`
	// Specifies the shard number
	ShardNumber   uint64 `protobuf:"varint,2,opt,name=shard_number,json=shardNumber,proto3" json:"shard_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectionId) Reset() {
	*x = ProjectionId{}
	mi := &file_ego_ego_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionId) ProtoMessage() {}

func (x *ProjectionId) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionId.ProtoReflect.Descriptor instead.
func (*ProjectionId) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectionId) GetProjectionName() string {
	if x != nil {
		return x.ProjectionName
	}
	return ""
}

func (x *ProjectionId) GetShardNumber() uint64 {
	if x != nil {
		return x.ShardNumber
	}
	return 0
}

// DurableState defines the durable state behavior
// actor
type DurableState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the persistence unique identifier
	PersistenceId string `protobuf:"bytes,1,opt,name=persistence_id,json=persistenceId,proto3" json:"persistence_id,omitempty"`
	// Specifies the version number
	VersionNumber uint64 `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	// the state obtained from processing a command
	ResultingState *anypb.Any `protobuf:"bytes,3,opt,name=resulting_state,json=resultingState,proto3" json:"resulting_state,omitempty"`
	// Specifies the timestamp
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Specifies the shard number
	Shard         uint64 `protobuf:"varint,6,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurableState) Reset() {
	*x = DurableState{}
	mi := &file_ego_ego_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurableState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableState) ProtoMessage() {}

func (x *DurableState) ProtoReflect() protoreflect.Message {
	mi := &file_ego_ego_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableState.ProtoReflect.Descriptor instead.
func (*DurableState) Descriptor() ([]byte, []int) {
	return file_ego_ego_proto_rawDescGZIP(), []int{8}
}

func (x *DurableState) GetPersistenceId() string {
	if x != nil {
		return x.PersistenceId
	}
	return ""
}

func (x *DurableState) GetVersionNumber() uint64 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *DurableState) GetResultingState() *anypb.Any {
	if x != nil {
		return x.ResultingState
	}
	return nil
}

func (x *DurableState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DurableState) GetShard() uint64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

var File_ego_ego_proto protoreflect.FileDescriptor

const file_ego_ego_proto_rawDesc = "" +
	"\n" +
	"\rego/ego.proto\x12\x05egopb\x1a\x19google/protobuf/any.proto\"\x95\x02\n" +
	"\x05Event\x12%\n" +
	"\x0epersistence_id\x18\x01 \x01(\tR\rpersistenceId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x03 \x01(\bR\tisDeleted\x12*\n" +
	"\x05event\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05event\x12=\n" +
	"\x0fresulting_state\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x0eresultingState\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05shard\x18\a \x01(\x04R\x05shard\"\x83\x01\n" +
	"\fCommandReply\x124\n" +
	"\vstate_reply\x18\x01 \x01(\v2\x11.egopb.StateReplyH\x00R\n" +
	"stateReply\x124\n" +
	"\verror_reply\x18\x02 \x01(\v2\x11.egopb.ErrorReplyH\x00R\n" +
	"errorReplyB\a\n" +
	"\x05reply\"\xa6\x01\n" +
	"\n" +
	"StateReply\x12%\n" +
	"\x0epersistence_id\x18\x01 \x01(\tR\rpersistenceId\x12*\n" +
	"\x05state\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05state\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"&\n" +
	"\n" +
	"ErrorReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\t\n" +
	"\aNoReply\"\x11\n" +
	"\x0fGetStateCommand\"\x88\x01\n" +
	"\x06Offset\x12!\n" +
	"\fshard_number\x18\x01 \x01(\x04R\vshardNumber\x12'\n" +
	"\x0fprojection_name\x18\x02 \x01(\tR\x0eprojectionName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"Z\n" +
	"\fProjectionId\x12'\n" +
	"\x0fprojection_name\x18\x01 \x01(\tR\x0eprojectionName\x12!\n" +
	"\fshard_number\x18\x02 \x01(\x04R\vshardNumber\"\xcf\x01\n" +
	"\fDurableState\x12%\n" +
	"\x0epersistence_id\x18\x01 \x01(\tR\rpersistenceId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x04R\rversionNumber\x12=\n" +
	"\x0fresulting_state\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x0eresultingState\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05shard\x18\x06 \x01(\x04R\x05shardBs\n" +
	"\tcom.egopbB\bEgoProtoH\x02P\x01Z&github.com/tochemey/ego/v3/egopb;egopb\xa2\x02\x03EXX\xaa\x02\x05Egopb\xca\x02\x05Egopb\xe2\x02\x11Egopb\\GPBMetadata\xea\x02\x05Egopbb\x06proto3"

var (
	file_ego_ego_proto_rawDescOnce sync.Once
	file_ego_ego_proto_rawDescData []byte
)

func file_ego_ego_proto_rawDescGZIP() []byte {
	file_ego_ego_proto_rawDescOnce.Do(func() {
		file_ego_ego_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ego_ego_proto_rawDesc), len(file_ego_ego_proto_rawDesc)))
	})
	return file_ego_ego_proto_rawDescData
}

var file_ego_ego_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ego_ego_proto_goTypes = []any{
	(*Event)(nil),           // 0: egopb.Event
	(*CommandReply)(nil),    // 1: egopb.CommandReply
	(*StateReply)(nil),      // 2: egopb.StateReply
	(*ErrorReply)(nil),      // 3: egopb.ErrorReply
	(*NoReply)(nil),         // 4: egopb.NoReply
	(*GetStateCommand)(nil), // 5: egopb.GetStateCommand
	(*Offset)(nil),          // 6: egopb.Offset
	(*ProjectionId)(nil),    // 7: egopb.ProjectionId
	(*DurableState)(nil),    // 8: egopb.DurableState
	(*anypb.Any)(nil),       // 9: google.protobuf.Any
}
var file_ego_ego_proto_depIdxs = []int32{
	9, // 0: egopb.Event.event:type_name -> google.protobuf.Any
	9, // 1: egopb.Event.resulting_state:type_name -> google.protobuf.Any
	2, // 2: egopb.CommandReply.state_reply:type_name -> egopb.StateReply
	3, // 3: egopb.CommandReply.error_reply:type_name -> egopb.ErrorReply
	9, // 4: egopb.StateReply.state:type_name -> google.protobuf.Any
	9, // 5: egopb.DurableState.resulting_state:type_name -> google.protobuf.Any
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ego_ego_proto_init() }
func file_ego_ego_proto_init() {
	if File_ego_ego_proto != nil {
		return
	}
	file_ego_ego_proto_msgTypes[1].OneofWrappers = []any{
		(*CommandReply_StateReply)(nil),
		(*CommandReply_ErrorReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ego_ego_proto_rawDesc), len(file_ego_ego_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ego_ego_proto_goTypes,
		DependencyIndexes: file_ego_ego_proto_depIdxs,
		MessageInfos:      file_ego_ego_proto_msgTypes,
	}.Build()
	File_ego_ego_proto = out.File
	file_ego_ego_proto_goTypes = nil
	file_ego_ego_proto_depIdxs = nil
}
