// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: sample/sample.proto

package samplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_sample_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_sample_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_sample_sample_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_sample_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_sample_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_sample_sample_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountBalance float64                `protobuf:"fixed64,2,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_sample_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_sample_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_sample_sample_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetAccountBalance() float64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

type CreateAccount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountBalance float64                `protobuf:"fixed64,2,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccount) Reset() {
	*x = CreateAccount{}
	mi := &file_sample_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount) ProtoMessage() {}

func (x *CreateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_sample_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount.ProtoReflect.Descriptor instead.
func (*CreateAccount) Descriptor() ([]byte, []int) {
	return file_sample_sample_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccount) GetAccountBalance() float64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

type CreditAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditAccount) Reset() {
	*x = CreditAccount{}
	mi := &file_sample_sample_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccount) ProtoMessage() {}

func (x *CreditAccount) ProtoReflect() protoreflect.Message {
	mi := &file_sample_sample_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccount.ProtoReflect.Descriptor instead.
func (*CreditAccount) Descriptor() ([]byte, []int) {
	return file_sample_sample_proto_rawDescGZIP(), []int{4}
}

func (x *CreditAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreditAccount) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type AccountCreated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountBalance float64                `protobuf:"fixed64,2,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountCreated) Reset() {
	*x = AccountCreated{}
	mi := &file_sample_sample_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreated) ProtoMessage() {}

func (x *AccountCreated) ProtoReflect() protoreflect.Message {
	mi := &file_sample_sample_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreated.ProtoReflect.Descriptor instead.
func (*AccountCreated) Descriptor() ([]byte, []int) {
	return file_sample_sample_proto_rawDescGZIP(), []int{5}
}

func (x *AccountCreated) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountCreated) GetAccountBalance() float64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

type AccountCredited struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountBalance float64                `protobuf:"fixed64,2,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountCredited) Reset() {
	*x = AccountCredited{}
	mi := &file_sample_sample_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCredited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCredited) ProtoMessage() {}

func (x *AccountCredited) ProtoReflect() protoreflect.Message {
	mi := &file_sample_sample_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCredited.ProtoReflect.Descriptor instead.
func (*AccountCredited) Descriptor() ([]byte, []int) {
	return file_sample_sample_proto_rawDescGZIP(), []int{6}
}

func (x *AccountCredited) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountCredited) GetAccountBalance() float64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

var File_sample_sample_proto protoreflect.FileDescriptor

const file_sample_sample_proto_rawDesc = "" +
	"\n" +
	"\x13sample/sample.proto\x12\bsamplepb\"\x16\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05reply\x18\x02 \x01(\tR\x05reply\"Q\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0faccount_balance\x18\x02 \x01(\x01R\x0eaccountBalance\"W\n" +
	"\rCreateAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0faccount_balance\x18\x02 \x01(\x01R\x0eaccountBalance\"H\n" +
	"\rCreditAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"X\n" +
	"\x0eAccountCreated\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0faccount_balance\x18\x02 \x01(\x01R\x0eaccountBalance\"Y\n" +
	"\x0fAccountCredited\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0faccount_balance\x18\x02 \x01(\x01R\x0eaccountBalanceB\x9a\x01\n" +
	"\fcom.samplepbB\vSampleProtoH\x02P\x01Z;github.com/tochemey/goakt/examples/protos/samplepb;samplepb\xa2\x02\x03SXX\xaa\x02\bSamplepb\xca\x02\bSamplepb\xe2\x02\x14Samplepb\\GPBMetadata\xea\x02\bSamplepbb\x06proto3"

var (
	file_sample_sample_proto_rawDescOnce sync.Once
	file_sample_sample_proto_rawDescData []byte
)

func file_sample_sample_proto_rawDescGZIP() []byte {
	file_sample_sample_proto_rawDescOnce.Do(func() {
		file_sample_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_sample_proto_rawDesc), len(file_sample_sample_proto_rawDesc)))
	})
	return file_sample_sample_proto_rawDescData
}

var file_sample_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sample_sample_proto_goTypes = []any{
	(*Ping)(nil),            // 0: samplepb.Ping
	(*Pong)(nil),            // 1: samplepb.Pong
	(*Account)(nil),         // 2: samplepb.Account
	(*CreateAccount)(nil),   // 3: samplepb.CreateAccount
	(*CreditAccount)(nil),   // 4: samplepb.CreditAccount
	(*AccountCreated)(nil),  // 5: samplepb.AccountCreated
	(*AccountCredited)(nil), // 6: samplepb.AccountCredited
}
var file_sample_sample_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sample_sample_proto_init() }
func file_sample_sample_proto_init() {
	if File_sample_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_sample_proto_rawDesc), len(file_sample_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sample_sample_proto_goTypes,
		DependencyIndexes: file_sample_sample_proto_depIdxs,
		MessageInfos:      file_sample_sample_proto_msgTypes,
	}.Build()
	File_sample_sample_proto = out.File
	file_sample_sample_proto_goTypes = nil
	file_sample_sample_proto_depIdxs = nil
}
