name: pull_request

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/readme.md'
      - '**/renovate.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: false
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - run: go version
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Vendoring and Tidy
        run: go mod tidy && go mod vendor
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
          args: --timeout 10m --config .golangci.yml
      - name: Run tests
        shell: bash
        run: |
          PKGS=$(go list -mod=vendor ./... | grep -v -E "(egopb|test|example|mocks)")
          go test -mod=vendor -p 1 -timeout 0 -race -v \
            -coverprofile=coverage.out -covermode=atomic \
            -coverpkg=$(echo $PKGS | tr ' ' ',') \
            $PKGS
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: false # optional (default = false)
